export {default as Home} from './home/Home'
export {default as Contact} from './contact/Contact'
export {default as Cart} from './cart/Cart'
export {default as Admin} from './admin/Admin'
export {default as orderHistory} from './orderHistory/OrderHistory'